### ISSUE TITLE
Ability to change fibers color

### ISSUE THREAD

**Issue by hpcowley** [aplbrain/pytri#105]
`c` exists as an argument in the pytri api (`fibers`) but it is not used in `FiberLayer.js`. We should pass the color given onward!

**Comment by j6k4m8** [comment]
See also #104 and #108

**Comment by j6k4m8** [comment]
This is now supported with the new `lines` API:

```python
Figure@lines(..., colors=List[List[Tuple[float, float, float], Tuple[float, float, float]]] | List[List[Tuple[float, float, float]]])
```

If you pass a list like this,

```python
[
    [1, 0, 0], # line 1
    [0, 0, 1], # line 2
]
```

Then the first line will be red and the second line will be blue.

If you pass a list like this,

```python
[
    [[1, 0, 0], [0, 1, 0]], # line 1
    [[0, 1, 0], [0, 0, 1]], # line 2
]
```

Then the first line will fade gradually from red to green, and the second line will fade gradually from green to blue.
