### ISSUE TITLE
Require NetworkX >=2.0

### ISSUE THREAD

**Issue by hpcowley** [aplbrain/pytri#107]
NetworkX 1.X has unexpected behavior when converting graphs to JSON using `json_graph.node_link_data()`. I've found that it ignores node IDs when creating `links`. This causes the `links` to specify `source` and `target` nodes based on their 0-based index in the list of nodes, which breaks `graph` functionality (which expects source and target to be node IDs).

**Comment by j6k4m8** [comment]
This is the node_link API, which uses index-based edge targets. Happy to answer questions about this offline, closing for now.
