### ISSUE TITLE
An error in the tutorial

### ISSUE THREAD

**Issue by vinuvargheseijk** [aplbrain/pytri#124]
for z in range(small.shape[0]):
    for y in range(small.shape[1]):
        for x in range(small.shape[2]):
            coords.append((x, y, z*10))

f = Figure()
f.scatter(coords, color=[[i,i,i] for i in small.ravel()], attenuate_size=True, size=5)
f.show()

I think 'small' should  be 'em_excerpt'

**Comment by j6k4m8** [comment]
Thank you so much for pointing this out, @vinuvargheseijk! I just made #125 to fix this :)
